name: Docker Build

on:
  push:
    branches:
    - master

permissions:
  contents: read
  packages: write

jobs:
  docker-build:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'e621ng'

    steps:
      - uses: e621ng/e621ng/.github/docker-build-and-push@master
